targets:
  $default:
    sources:
      - routes/**
      - $package$
      - lib/$lib$
    builders:
      open_api_spec_builder_generator|open_api_fragment_builder:
        options:
          apiLibrary: "dartFrog"