targets:
  $default:
    sources:
      - routes/**
      - $package$
      - lib/$lib$
    builders:
      openapi_document_generator|openapi_fragment_builder:
        options:
          apiLibrary: "dartFrog"